@startuml
!pragma teoz true

actor Client as Client order 01

box "MIB" #HoneyDew

        box "Mobile" #Linen
            participant "Mobile" as Mobile order 05
        end box

    participant "Product\nRequest" as Request order 10
    participant "Transfer\nService" as Transfer order 20
    participant "Payment\nService" as Payment order 30
    participant "Directory\nService" as Directory order 40
    participant "Admin\nPanel" as Admin order 50
    participant "Banner\nService" as Banner order 60
    participant "Cashback\nService" as Cashback order 70
    participant "Chat\nService" as Chat order 80
    participant "Discount\nCard" as Discount order 90
    participant "Document\nService" as Document order 100
    participant "File\nService" as File order 110
    participant "History" as History order 120
    participant "Important\nNotice" as IS order 130
    participant "Notification" as Notification order 140
    database "Notification\nDatabase" as NotificationDB order 145
    participant "Profile\nService" as Profile order 150
    participant "Receipt\nService" as Receipt order 160
    participant "Registration\nService" as Registration order 170
    participant "Service\nCatalog" as Service order 180
    participant "Template\nService" as Template order 190
    participant "Auth\nService" as Auth order 200
    queue "Kafka" as Kafka order 210
    participant "Limit\nService" as Limit order 220
    participant "Version\nControl" as Version order 230

      box "Integration" #Linen
        participant "Integration\nService" as Integration order 240
      end box

end box

box "Bank" #MintCream

    participant "Processing" as Processing order 300
    participant "OnlineBank.WebAPI" as WebAPI order 310
    database "OnlineBank DB" as OBDB order 320
    participant "Processing Gate" as Pgate order 330
    participant "OnlineBank.IntegrationService" as OBIS order 340
    participant "Bank Bus" as BankBus order 350
    participant "BakaiAPI" as BakaiAPI order 360
    participant "Proposal" as Proposal order 370
    participant "gRPC Notification Service" as gRPCNotification order 380

end box
@enduml
