@startuml
!pragma teoz true

actor Client as Client order 10

box "MIB" #HoneyDew

        box "Mobile" #Linen
            participant "Mobile" as Mobile order 20
        end box

    participant "Admin\nPanel" as Admin order 30
    participant "Auth\nService" as Auth order 33
    participant "Banner\nService" as Banner order 36
    participant "Cashback\nService" as Cashback order 39
    participant "Chat\nService" as Chat order 42
    participant "Directory\nService" as Directory order 45
    participant "Discount\nCard" as Discount order 48
    participant "Document\nService" as Document order 51
    participant "File\nService" as File order 54
    participant "History" as History order 57
    participant "Important\nNotice" as IS order 60
    participant "Integration\nService" as Integration order 63
    queue "Kafka" as Kafka order 45
    participant "Limit\nService" as Limit order 66
    participant "Notification" as Notification order 70
    participant "Payment\nService" as Payment order 73
    participant "Product\nRequest" as Request order 76
    participant "Profile\nService" as Profile order 79
    participant "Receipt\nService" as Receipt order 82
    participant "Registration\nService" as Registration order 85
    participant "Service\nCatalog" as Service order 88
    participant "Template\nService" as Template order 91
    participant "Transfer\nService" as Transfer order 94
    participant "Version\nControl" as Version order 97
end box

box "Bank" #MintCream

    participant "Processing" as Processing order 100
    participant "OnlineBank.WebAPI" as WebAPI order 110
    database "OnlineBank DB" as OBDB order 120
    participant "Processing Gate" as Pgate order 130
    participant "OnlineBank.IntegrationService" as OBIS order 140
    participant "Bank Bus" as BankBus order 150
    participant "BakaiAPI" as BakaiAPI order 160
    participant "Proposal" as Proposal order 170

end box
@enduml
