@startuml
!pragma teoz true

actor Оператор as User order 10

box "SDP" #HoneyDew

        box "Frontend" #Linen
            participant "Mobile" as Mobile order 20
            participant "Web" as Web order 25
            participant "KoronaPay iFrame" as ZK order 30
        end box

    participant "Admin\nPanel" as Admin order 40
    participant "Auth\nService" as Auth order 50
    participant "Client\nService" as Client order 60
    participant "Directory\nService" as Directory order 70
    participant "Transfer\nSevice" as Core order 80
    queue "Kafka" as Kafka order 90

      box "Integration" #Linen
        participant "Integration\nService" as Integration order 100
      end box

end box

box "External Services" #MintCream

    participant "OnlineBank.WebAPI" as OBWA order 110
    participant "OnlineBank.IntegrationService" as OBIS order 120
    participant "KoronaPay" as korona order 150

end box

@enduml
